name = "raris-cark"
workers_dev = true
compatibility_date = "2023-09-01"
main = "dist/index.js"

[site]
bucket = "./dist/public"

[build]
command = "npm run build"

# Simplified configuration without any extra fields
# Removed all environments to avoid any routing or KV namespace issues

# Secrets that need to be set
# - SESSION_SECRET
# - DATABASE_URL
