name = "raris-cark"
workers_dev = true
compatibility_date = "2023-09-01"
main = "dist/index.js"

[site]
bucket = "./dist/public"

[build]
command = "npm run build"

[env.production]
name = "raris-cark-prod"
route = "https://raris-cark.n2ngamingsolutions.workers.dev/*"

[env.staging]
name = "raris-cark-staging"

# Secrets that need to be set
# - SESSION_SECRET
# - DATABASE_URL
